from typing import IO, Any, overload
from _io import _IOBase
from os import PathLike


_CharType = int | float | str | bytes
_FileType = PathLike | str | bytes
_IOType = IO | _IOBase

class char(str, int, bytes):
    _CharType |= char
    def __add__(self, other: _CharType) -> char:...
    def __radd__(self, other: _CharType) -> _CharType:...
    def __init__(self, __obj: _CharType) -> None:...
    def __int__(self) -> int:...
    def __str__(self) -> str:...
    def __bytes__(self) -> bytes:...

def getchar(file: _FileType, size: int = 1) -> str:...

class PyIstream:
    filename: _FileType
    file: _IOType
    @overload
    def __init__(self, file: _FileType, *args: Any, **kwargs: Any) -> None:...
    @overload
    def __init__(self, file: _IOType) -> None:...
    @overload
    def get(self, size: int) -> _CharType:...
    @overload
    def get(self, *end: list | tuple, size: int = -1) -> _CharType:...
    def __rshift__(self, other: list | tuple | int) -> _CharType:...
    __call__ = get
    __lshift__ = __rshift__
    def close(self) -> None:...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:...

pycin: PyIstream

def globalization(x: type) -> type:...
