_CharType = int | float | str | bytes
class char(str, int, bytes):
    _CharType |= char
    def __add__(self, other: _CharType) -> char:...
    def __radd__(self, other: _CharType) -> _CharType:...
    def __init__(self, __obj: _CharType) -> None:...
    def __int__(self) -> int:...
    def __str__(self) -> str:...
    def __bytes__(self) -> bytes:...

def globalization(x: type) -> type:...
