from typing import List

userfile: str

def random_string() -> str:...
def get_random_file() -> str:...

def change_display_file(file: str, display: bool) -> None:...
def keywords(file: str) -> str:...
def seek(
        filename: str,
        *seekdirs: str,
        eq: bool = False,
        findone: bool = False,
) -> str | List[str]:...