def system(name: str) -> int:...
def to_cmd(name: str) -> int:...
def install (name: str, file: str | None = None) ->                  None:...
def upgrade (name: str, file: str | None = None) ->                  None:...
def unistall(name: str, file: str | None = None, show: bool=True) -> None:...

class InstallError(Exception):
    def __init__(self, name: str) -> None:...
    __module__: str

class UninstallError(Exception):
    def __init__(self, name: str) -> None:...
    __module__: str