from typing import IO, Any, Optional
from playwright.sync_api import Page as _Page


class UserError(Exception):
    def __init__(self) -> None: ...

def set_user(page: str, new_username: str = ..., new_password: str = ..., username: str = ..., password: str = ...) -> None: ...

class Note:
    def __init__(self, page: str, username: str, password: str) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Note: ...
    def __exit__(self, exc_type: Optional[Any], exc_val: Optional[Any], exc_tb: Optional[Any]) -> None: ...

    # Methods from buffer (io.StringIO)
    def write(self, s: str) -> int: ...
    def writelines(self, lines: list[str]) -> None: ...
    def read(self, size: int = ...) -> str: ...
    def readline(self, limit: int = ...) -> str: ...
    def readlines(self, hint: int = ...) -> list[str]: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def tell(self) -> int: ...
    def truncate(self, size: Optional[int] = ...) -> int: ...
    def getvalue(self) -> str: ...
