from io import BytesIO
from pydub import AudioSegment
from numpy import floating
from pyttsx3.engine import Engine
from typing import Dict, Tuple


SR: int
CH: int
FM: int
FMN: floating
MUSICSUFFIX: str
tts: Engine

class Sound:
    suffix: str
    data: BytesIO
    def __init__(self, file: str) -> None:...
    def speed_change(self, speed: float, file: str) -> Sound:...
    def play(self, cnt: int = 1, speed: float = 1, newthread: bool = False, daemon: bool = True) -> None:...
    def __add__(self, other: Sound) -> Sound:...
    def overlay(self, other: Sound, postion: float = 0, loop: bool = False, times: int = None, gain_during_overlay: int = None) -> Sound:...
    def from_file(self) -> AudioSegment:...
    def __len__(self) -> float:...

def recording(st: int, sr: int = SR, ch: int = CH, format: int = FM, file: str = None) -> Sound:...

A: int
B: int
C: int
D: int
E: int
F: int
G: int
tunes: Dict[str, int]
tune: int
additionals: Dict[str | None, int]
bpm: int

def set_tune(value: str | int) -> None:...
def get_tune(value: int = None) -> str:...

class MusicalNote:
    scale: int
    note: int
    beat: int
    def __init__(self, scale: int, note: int, additional: str = None, beat: int = 80) -> None:...
    def __add__(self, other: float) -> float:...
    def __sub__(self, other: MusicalNote | float) -> float | MusicalNote:...
    def __radd__(self, other: float) -> float:...
    def __rsub__(self, other: float) -> MusicalNote:...
    def __float__(self) -> float:...
    def __int__(self) -> int:...
    
    def play_frequency(self) -> Tuple[int, int]:...

A4: MusicalNote
def play_music(*musicalnotes, file: str = None) -> Sound:...
def say(text: str, file: str = None) -> Sound:...